
const char INDEX_HTML[] =
"<!DOCTYPE HTML>"
"<html>"
"<head>"
"<meta name = \"viewport\" content = \"width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable=0\">"
"<title>Dingus</title>"
"<style>"
"html { background-color: #fff;}"
"body { background-color: #efefef; font-family: Arial, Helvetica, Sans-Serif; color: #000000; width: 80%; max-width: 900px; margin: 0 auto; padding: 2em; }"
"h1 { text-align: center;}"
"</style>"
"</head>"
"<body>"
"<h1>Hello Dingus!</h1>"
"<FORM action=\"/\" method=\"post\">"
"<P>"
"<h2>LED</h2>" 
"<INPUT type=\"radio\" name=\"LED\" value=\"1\">On<BR>"
"<INPUT type=\"radio\" name=\"LED\" value=\"0\">Off<BR>"
"<INPUT type=\"submit\" value=\"Send\"> <INPUT type=\"reset\">"
"</P>"
"</FORM>"
"</body>"
"</html>";
